# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Bump Version 

on: 
    workflow_dispatch:
        
    push:
        branches: [ master ]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump Version
        id: increment-git-tag
        run: |
          bash ./build/git_bump_version.sh -v patch