name: 'test'

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    strategy:
      fail-fast: false

      matrix:
        redis:
        - '6.0'
        - '5.0'

    runs-on: 'ubuntu-latest'

    services:
      redis:
        image: 'bitnami/redis:${{ matrix.redis }}'
        env:
          REDIS_PASSWORD: testing123
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - '6379:6379'

    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'actions/setup-go@v3'
        with:
          go-version: '1.24'

      - run: 'go mod download'

      # - uses: 'golangci/golangci-lint-action@v3'
      #   with:
      #     only-new-issues: 'true'
      #     skip-cache: 'true'

      - run: 'make test-acc'
        env:
          REDIS_HOST: '127.0.0.1'
          REDIS_PORT: '6379'
          REDIS_PASS: 'testing123'
